services:
  chatbuddy:
    image: ghcr.io/sjroesink/chatbuddy:latest
    container_name: chatbuddy
    restart: unless-stopped
    env_file: .env
#    volumes:
#      - /mnt/user/appdata/chatbuddy:/app/data
#    environment:
#      - DATABASE_PATH=/app/data/bot.db
